development:
  adapter: mysql2
  encoding: utf8
  reconnect: true
  pool: 5
  host: <%= ENV['DEV_DATABASE_HOST'] || '127.0.0.1' %>
  database: <%= ENV['DEV_DATABASE_NAME'] || 'kunstuitleen' %>
  username: <%= ENV['DEV_DATABASE_USERNAME'] || 'root' %>
  password: <%= ENV['DEV_DATABASE_PASSWORD'] || '' %>
